### PR TITLE
Remove the extra `

### PR DESCRIPTION
**Pull request by yihui**
https://github.com/yihui/knitr/issues/2057

It will be great if you could make a CRAN release at some time after merging this PR. Thank you!

### CODE REVIEW

**Comment by TomKellyGenetics** [comment]
Thank you for notifying us @yihui! I received your email and have planned to amend this on the next CRAN release. Since expected updates to dependencies discussed in #1 are now available, I will be submitting a release in the near future.

Sorry it may some time and for the delayed response. I developed this package in my previous position and I am busy with the duties of my new job.

**Comment by yihui** [comment]
No worries at all! Please take your time. Thanks!

**Comment by TomKellyGenetics** [comment]
I've committed this change to master here (thanks for the reminder by email). It will be resolved in the next release on CRAN.
https://github.com/TomKellyGenetics/leiden/commit/7e3e007b6fad624b684836754892b67370c51168

Sorry it appears this PR was merged into version 0.3.10 but was not included in the development version so version 0.4.2 which includes major changes did not resolve the issue. https://github.com/TomKellyGenetics/leiden/releases/tag/0.4.2

Apologies for the confusion, this is a result of changes that depended on updates to igraph which took a long time to release. https://github.com/TomKellyGenetics/leiden/issues/1

**Comment by yihui** [comment]
Oh I have completely forgotten that I had a PR here :)

No worries, and thanks!

**Comment by TomKellyGenetics** [comment]
Release v0.4.3.1 which resolves this is on it's way to CRAN

**Comment by yihui** [comment]
Perfect!

**Comment by TomKellyGenetics** [comment]
Live on CRAN today. Minor delays due to updates in their citation checks and reverse dependencies failing with Seurat v4.4.0. Seems to be an unrelated issue to changes in this package so CRAN overlords approved it.

**Comment by yihui** [comment]
Great! Thanks for the update!

**Pull request merged**
